### ISSUE TITLE
No grades page enhancements work

### ISSUE THREAD

**Issue by ajsirota** [aopell/SchoologyPlus#309]
### Describe the bug
When I open the grades page, none of S+'s enhancements appear, but my theme and the `(+)` settings button show.

### Steps to reproduce
1. Open the grade report or a course's grades page
2. Observe that none of S+'s enhancements appear

### Expected behavior
To be able to see S+'s enhancements, including the percentage without expanding the course and the what-if mode checkbox.

### Additional context
It appears that the grades script is loading in before jQuery, because I see these errors in the console:
```
Uncaught ReferenceError: $ is not defined
    at grades.js:25:1
Uncaught ReferenceError: modals is not defined
    at course.js:27:5
    at course.js:79:3
```

### Platform
I'm using Arc 0.91.1, which is based on Chromium 112.0.5615.49. My Schoology domain is a custom subdomain of `.schoology.com`, and S+ is version 7.8.1.

**Comment by aopell** [comment]
Yeah unfortunately this is a known bug that I've spent a fair bit of time trying to understand, but I've made no progress. It seems to be a random thing that happens, and most of the time it's fixed by disabling and re-enabling the extension.

Unfortunately I don't have much helpful info beyond that right now.
